---
- hosts: localhost
  tasks:
    - name: Create an object
      ansible.builtin.lineinfile:
        path: artifact.txt
        line: Hello there
        create: yes
        
    - command: find / -name "result" 
