---
- hosts: localhost
  tasks:
    - name: Create an object
      ansible.builtin.lineinfile:
        path: artifact.txt
        line: Hello there
        create: yes
        
    - command: 'microdnf install findutils ; find / -name "result"' 
